/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import dao.GameDao;
import dao.MatchDao;
import java.awt.Font;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JTable;
import model.Game;
import model.GameTableModel;
import model.Match;

/**
 *
 * @author stim
 */
public class GamesPaid extends javax.swing.JPanel {

    private static int currentBoard;
    private static HashSet<Integer> payListA = new HashSet<>();
    private static HashSet<Integer> payListB = new HashSet<>();
    private static HashSet<Integer> payListC = new HashSet<>();
    private static HashSet<Integer> payListD = new HashSet<>();

    private static ArrayList<Game> gameListA;
    private static ArrayList<Game> gameListB;
    private static ArrayList<Game> gameListC;
    private static ArrayList<Game> gameListD;

    private static boolean latchForTabs;

    /**
     * Creates new form GamePayment
     */
    public GamesPaid() {

        prepareComponents();
        initComponents();
        jTable1.setRowSelectionAllowed(true);
        Font font = new Font("Verdana", Font.CENTER_BASELINE, 14);
        jTable1.setFont(font);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

    }

    private void prepareComponents() {

        gameListA = new GameDao().getAllPaidGames("BOARD-A");
        payListA.clear();
        gameListB = new GameDao().getAllPaidGames("BOARD-B");
        payListB.clear();
        gameListC = new GameDao().getAllPaidGames("BOARD-C");
        payListC.clear();
        gameListD = new GameDao().getAllPaidGames("BOARD-D");
        payListD.clear();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneBoard = new javax.swing.JTabbedPane();
        tabBoardA = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblGames = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        paidBy = new javax.swing.JTextField();
        paidRemark = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        payAmount = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        payDiscount = new javax.swing.JTextField();
        lblPayStatus = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblPaidAmount = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblDiscountedAmount = new javax.swing.JLabel();
        tabBoardB = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblGames1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblAmount1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        paidBy1 = new javax.swing.JTextField();
        paidRemark1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        payAmount1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        lblTime1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        payDiscount1 = new javax.swing.JTextField();
        lblPayStatus1 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblPaidAmount1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lblDiscountedAmount1 = new javax.swing.JLabel();
        tabBoardC = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        lblGames2 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lblAmount2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        paidBy2 = new javax.swing.JTextField();
        paidRemark2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        payAmount2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        payDiscount2 = new javax.swing.JTextField();
        lblPayStatus2 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lblPaidAmount2 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lblDiscountedAmount2 = new javax.swing.JLabel();
        tabBoardD = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        lblGames3 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lblAmount3 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        paidBy3 = new javax.swing.JTextField();
        paidRemark3 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        payAmount3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        lblTime3 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        payDiscount3 = new javax.swing.JTextField();
        lblPayStatus3 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        lblPaidAmount3 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        lblDiscountedAmount3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        tabbedPaneBoard.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneBoardStateChanged(evt);
            }
        });
        tabbedPaneBoard.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabbedPaneBoardComponentShown(evt);
            }
        });
        tabbedPaneBoard.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabbedPaneBoardPropertyChange(evt);
            }
        });

        jTable1.setModel(new GameTableModel(gameListA));
        jTable1.setCellSelectionEnabled(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText("Total Games:");

        lblGames.setText(".......");

        jLabel3.setText("Total Amount:");

        lblAmount.setText(".........");

        jLabel5.setText("Payer");

        jLabel6.setText("Remark");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel25.setText("Paid Amount:");

        jLabel26.setText("Total Time:");

        lblTime.setText("..........");

        jLabel27.setText("Discount");

        lblPayStatus.setText("Status: ");

        jLabel28.setText("Paid Amount");

        lblPaidAmount.setText("..........");

        jLabel29.setText("Discounted");

        lblDiscountedAmount.setText("..........");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGames, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(payAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(lblPayStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel26))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(payDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDiscountedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 22, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(paidBy, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paidRemark)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(lblDiscountedAmount))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(lblPaidAmount))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(lblAmount)
                        .addComponent(jLabel26)
                        .addComponent(lblTime)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(payDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(payAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(paidBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(paidRemark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(lblPayStatus))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout tabBoardALayout = new javax.swing.GroupLayout(tabBoardA);
        tabBoardA.setLayout(tabBoardALayout);
        tabBoardALayout.setHorizontalGroup(
            tabBoardALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoardALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabBoardALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabBoardALayout.setVerticalGroup(
            tabBoardALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoardALayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPaneBoard.addTab("BOARD-A", tabBoardA);

        jTable2.setModel(new GameTableModel(gameListB));
        jTable2.setCellSelectionEnabled(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("Total Games:");

        lblGames1.setText(".......");

        jLabel30.setText("Total Amount:");

        lblAmount1.setText(".........");

        jLabel31.setText("Payer");

        jLabel32.setText("Remark");

        jButton9.setText("Pay Amount");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel33.setText("Pay Amount:");

        jLabel34.setText("Total Time:");

        lblTime1.setText("..........");

        jLabel35.setText("Discount");

        lblPayStatus1.setText("Status: ");

        jLabel36.setText("Paid Amount");

        lblPaidAmount1.setText("..........");

        jLabel37.setText("Discounted");

        lblDiscountedAmount1.setText("..........");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(payAmount1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGames1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paidBy1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPaidAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDiscountedAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPayStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paidRemark1)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(payDiscount1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 355, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(lblDiscountedAmount1))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(lblPaidAmount1))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGames1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addComponent(lblAmount1)
                        .addComponent(jLabel34)
                        .addComponent(lblTime1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(payDiscount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(payAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(paidBy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(paidRemark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(lblPayStatus1))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout tabBoardBLayout = new javax.swing.GroupLayout(tabBoardB);
        tabBoardB.setLayout(tabBoardBLayout);
        tabBoardBLayout.setHorizontalGroup(
            tabBoardBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoardBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabBoardBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabBoardBLayout.setVerticalGroup(
            tabBoardBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoardBLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPaneBoard.addTab("BOARD-B", tabBoardB);

        jTable3.setModel(new GameTableModel(gameListC));
        jTable3.setCellSelectionEnabled(true);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        jLabel38.setText("Total Games:");

        lblGames2.setText(".......");

        jLabel39.setText("Total Amount:");

        lblAmount2.setText(".........");

        jLabel40.setText("Payer");

        jLabel41.setText("Remark");

        jButton11.setText("Pay Amount");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Refresh");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel42.setText("Pay Amount:");

        jLabel43.setText("Total Time:");

        lblTime2.setText("..........");

        jLabel44.setText("Discount");

        lblPayStatus2.setText("Status: ");

        jLabel45.setText("Paid Amount");

        lblPaidAmount2.setText("..........");

        jLabel46.setText("Discounted");

        lblDiscountedAmount2.setText("..........");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(payAmount2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGames2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel39))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paidBy2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPaidAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDiscountedAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel41))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPayStatus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paidRemark2)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(payDiscount2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 355, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46)
                        .addComponent(lblDiscountedAmount2))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(lblPaidAmount2))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGames2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39)
                        .addComponent(lblAmount2)
                        .addComponent(jLabel43)
                        .addComponent(lblTime2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(payDiscount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(payAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(paidBy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(paidRemark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(lblPayStatus2))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout tabBoardCLayout = new javax.swing.GroupLayout(tabBoardC);
        tabBoardC.setLayout(tabBoardCLayout);
        tabBoardCLayout.setHorizontalGroup(
            tabBoardCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoardCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabBoardCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabBoardCLayout.setVerticalGroup(
            tabBoardCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoardCLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPaneBoard.addTab("BOARD-C", tabBoardC);

        jTable4.setModel(new GameTableModel(gameListD));
        jTable4.setCellSelectionEnabled(true);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jLabel47.setText("Total Games:");

        lblGames3.setText(".......");

        jLabel48.setText("Total Amount:");

        lblAmount3.setText(".........");

        jLabel49.setText("Payer");

        jLabel50.setText("Remark");

        jButton13.setText("Pay Amount");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Refresh");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel51.setText("Pay Amount:");

        jLabel52.setText("Total Time:");

        lblTime3.setText("..........");

        jLabel53.setText("Discount");

        lblPayStatus3.setText("Status: ");

        jLabel54.setText("Paid Amount");

        lblPaidAmount3.setText("..........");

        jLabel55.setText("Discounted");

        lblDiscountedAmount3.setText("..........");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(payAmount3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGames3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel48))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paidBy3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblAmount3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPaidAmount3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDiscountedAmount3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel50))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPayStatus3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paidRemark3)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(payDiscount3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 355, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel55)
                        .addComponent(lblDiscountedAmount3))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel54)
                        .addComponent(lblPaidAmount3))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGames3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel48)
                        .addComponent(lblAmount3)
                        .addComponent(jLabel52)
                        .addComponent(lblTime3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(payDiscount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(payAmount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(paidBy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(paidRemark3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(lblPayStatus3))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout tabBoardDLayout = new javax.swing.GroupLayout(tabBoardD);
        tabBoardD.setLayout(tabBoardDLayout);
        tabBoardDLayout.setHorizontalGroup(
            tabBoardDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoardDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabBoardDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabBoardDLayout.setVerticalGroup(
            tabBoardDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoardDLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPaneBoard.addTab("BOARD-D", tabBoardD);

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Paid Games");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPaneBoard)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPaneBoard))
        );
    }// </editor-fold>//GEN-END:initComponents
//

    private void tabbedPaneBoardStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneBoardStateChanged
        // TODO add your handling code here:
        System.out.println("Hello");
        currentBoard = tabbedPaneBoard.getSelectedIndex();
        System.out.println("Current board: " + currentBoard);

    }//GEN-LAST:event_tabbedPaneBoardStateChanged

    //   Code not needed..
    private void tabbedPaneBoardComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabbedPaneBoardComponentShown
        // TODO add your handling code here:
        System.out.println("Check_1");
    }//GEN-LAST:event_tabbedPaneBoardComponentShown
 //   Code not needed..
    private void tabbedPaneBoardPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabbedPaneBoardPropertyChange
        // TODO add your handling code here:
        System.out.println("property changed");
        System.out.println(tabbedPaneBoard.getSelectedIndex());
        int tabIndex = tabbedPaneBoard.getSelectedIndex();


    }//GEN-LAST:event_tabbedPaneBoardPropertyChange

    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        jTable1.setRowSelectionInterval(row, row);
        jTable1.setColumnSelectionInterval(0, 10);
        // How to associate object with row
        Game g = null;
        switch (currentBoard) {
            case 0:
                g = gameListA.get(row);
                break;
            // find game wit row
            case 1:
                g = gameListB.get(row);
                break;
            case 2:
                g = gameListC.get(row);
                break;
            case 3:
                g = gameListD.get(row);
                break;
            default:
                System.out.println("Game not found!");
                g = new Game();
                break;
        }
       
        if (col == 10) {
            boolean value = (boolean) jTable1.getValueAt(row, col);
            System.out.println(value);
            
            if (!value && payListA.contains(row)) {
                payListA.remove(row);
                // remove when unchecked and set contains row
            } else if (value && !payListA.contains(row)) {
                payListA.add(row);
            } else {
                System.out.println("Doing nothing for " + value);
            }
            System.out.println(payListA);
          
            displayMatchDetail();
           
        } else {

            Match m = new MatchDao().getMatchById(g.getMatchId());
            String toolTip = "<html><head><title>Info</title></head><body><div style='border:2px solid black; font-size:18px;'>" + m.toString() + "</div></body></html>";
            jTable1.setToolTipText(toolTip);

        }
            jTable1.revalidate();
            jTable1.repaint();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // update selected game details for board1
       Game game = new Game();
       if(!payAmount.getText().equals("")){
           game.setAmount(Double.parseDouble(payAmount.getText()));
       }
       if(!payDiscount.getText().equals("")){
           game.setAmount(Double.parseDouble(payDiscount.getText()));
       }
       if(!paidBy.getText().equals("")){
           game.setAmount(Double.parseDouble(paidBy.getText()));
       }
       if(!paidRemark.getText().equals("")){
           game.setAmount(Double.parseDouble(paidRemark.getText()));
       }
       
       if(currentBoard==0 && payListA.size()>0){
           
           new GameDao().updateGame(game);
           
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        int col = jTable2.getSelectedColumn();
        jTable2.setRowSelectionInterval(row, row);
        jTable2.setColumnSelectionInterval(0, 10);
        // How to associate object with row
        Game g = null;
        switch (currentBoard) {
            case 0:
                g = gameListA.get(row);
                break;
            // find game wit row
            case 1:
                g = gameListB.get(row);
                break;
            case 2:
                g = gameListC.get(row);
                break;
            case 3:
                g = gameListD.get(row);
                break;
            default:
                System.out.println("Game not found!");
                g = new Game();
                break;
        }
       
        if (col == 10) {
            boolean value = (boolean) jTable2.getValueAt(row, col);
            System.out.println(value);
            
            if (!value && payListB.contains(row)) {
                payListB.remove(row);
                // remove when unchecked and set contains row
            } else if (value && !payListB.contains(row)) {
                payListB.add(row);
            } else {
                System.out.println("Doing nothing for " + value);
            }
            System.out.println(payListB);
          
            displayMatchDetail();
           
        } else {

            Match m = new MatchDao().getMatchById(g.getMatchId());
            String toolTip = "<html><head><title>Info</title></head><body><div style='border:2px solid black; font-size:18px;'>" + m.toString() + "</div></body></html>";
            jTable2.setToolTipText(toolTip);

        }
            jTable2.revalidate();
            jTable2.repaint();

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int row = jTable3.getSelectedRow();
        int col = jTable3.getSelectedColumn();
        jTable3.setRowSelectionInterval(row, row);
        jTable3.setColumnSelectionInterval(0, 10);
        // How to associate object with row
        Game g = null;
        switch (currentBoard) {
            case 0:
                g = gameListA.get(row);
                break;
            // find game wit row
            case 1:
                g = gameListB.get(row);
                break;
            case 2:
                g = gameListC.get(row);
                break;
            case 3:
                g = gameListD.get(row);
                break;
            default:
                System.out.println("Game not found!");
                g = new Game();
                break;
        }
       
        if (col == 10) {
            boolean value = (boolean) jTable3.getValueAt(row, col);
            System.out.println(value);
            
            if (!value && payListC.contains(row)) {
                payListC.remove(row);
                // remove when unchecked and set contains row
            } else if (value && !payListC.contains(row)) {
                payListC.add(row);
            } else {
                System.out.println("Doing nothing for " + value);
            }
            System.out.println(payListC);
          
            displayMatchDetail();
           
        } else {

            Match m = new MatchDao().getMatchById(g.getMatchId());
            String toolTip = "<html><head><title>Info</title></head><body><div style='border:2px solid black; font-size:18px;'>" + m.toString() + "</div></body></html>";
            jTable3.setToolTipText(toolTip);

        }
            jTable3.revalidate();
            jTable3.repaint();

    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        int row = jTable4.getSelectedRow();
        int col = jTable4.getSelectedColumn();
        jTable4.setRowSelectionInterval(row, row);
        jTable4.setColumnSelectionInterval(0, 10);
        // How to associate object with row
        Game g = null;
        switch (currentBoard) {
            case 0:
                g = gameListA.get(row);
                break;
            // find game wit row
            case 1:
                g = gameListB.get(row);
                break;
            case 2:
                g = gameListC.get(row);
                break;
            case 3:
                g = gameListD.get(row);
                break;
            default:
                System.out.println("Game not found!");
                g = new Game();
                break;
        }
       
        if (col == 10) {
            boolean value = (boolean) jTable4.getValueAt(row, col);
            System.out.println(value);
            
            if (!value && payListD.contains(row)) {
                payListD.remove(row);
                // remove when unchecked and set contains row
            } else if (value && !payListD.contains(row)) {
                payListD.add(row);
            } else {
                System.out.println("Doing nothing for " + value);
            }
            System.out.println(payListD);
          
            displayMatchDetail();
           
        } else {

            Match m = new MatchDao().getMatchById(g.getMatchId());
            String toolTip = "<html><head><title>Info</title></head><body><div style='border:2px solid black; font-size:18px;'>" + m.toString() + "</div></body></html>";
            jTable4.setToolTipText(toolTip);

        }
            jTable4.revalidate();
            jTable4.repaint();

    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

     private void displayMatchDetail() {
        int noOfGames = 0;
        int playTime = 0;
        double amount = 0.0;
        double paidAmount=0.0;
        double discountedAmount = 0.0;
        
        switch (currentBoard) {
            case 0:
                for (int i : payListA) {
                    noOfGames++;
                    Game g = gameListA.get(i);
                    Match m = new MatchDao().getMatchById(g.getMatchId());
                    amount += m.getRate() * g.getMatchTime();
                    paidAmount += g.getAmount();
                    discountedAmount += g.getDiscount();
                    playTime += g.getMatchTime();
                }
        lblGames.setText(Integer.toString(noOfGames));
        lblAmount.setText(Double.toString(amount));
        lblTime.setText(Integer.toString(playTime));
        lblPaidAmount.setText(Double.toString(paidAmount));
        lblDiscountedAmount.setText(Double.toString(discountedAmount));
                break;
            case 1:
                for (int i : payListB) {
                    noOfGames++; 
                    // should initialize / reset before loop begins
                    Game g = gameListB.get(i);
                    Match m = new MatchDao().getMatchById(g.getMatchId());
                    amount += m.getRate() * g.getMatchTime();
                    paidAmount += g.getAmount();
                    discountedAmount += g.getDiscount();
                    playTime += g.getMatchTime();
                }
                lblGames1.setText(Integer.toString(noOfGames));
        lblAmount1.setText(Double.toString(amount));
        lblTime1.setText(Integer.toString(playTime));
        lblPaidAmount1.setText(Double.toString(paidAmount));
        lblDiscountedAmount1.setText(Double.toString(discountedAmount));
                break;
                case 2:
                for (int i : payListC) {
                    noOfGames++;
                    Game g = gameListC.get(i);
                    Match m = new MatchDao().getMatchById(g.getMatchId());
                    amount += m.getRate() * g.getMatchTime();
                    paidAmount += g.getAmount();
                    discountedAmount += g.getDiscount();
                    playTime += g.getMatchTime();
                }
                lblGames2.setText(Integer.toString(noOfGames));
        lblAmount2.setText(Double.toString(amount));
        lblTime2.setText(Integer.toString(playTime));
        lblPaidAmount2.setText(Double.toString(paidAmount));
        lblDiscountedAmount2.setText(Double.toString(discountedAmount));
                break;
                case 3:
                for (int i : payListD) {
                    noOfGames++;
                    Game g = gameListD.get(i);
                    Match m = new MatchDao().getMatchById(g.getMatchId());
                    amount += m.getRate() * g.getMatchTime();
                    paidAmount += g.getAmount();
                    discountedAmount += g.getDiscount();
                    playTime += g.getMatchTime();
                }
                lblGames3.setText(Integer.toString(noOfGames));
        lblAmount3.setText(Double.toString(amount));
        lblTime3.setText(Integer.toString(playTime));
        lblPaidAmount3.setText(Double.toString(paidAmount));
        lblDiscountedAmount3.setText(Double.toString(discountedAmount));
                break;
                
            default:
                System.out.println("Display difficulty!");
                break;
        }
        
        // display Paid Amount, Discounted Amount 
        // payer name , remark as read only
        // then add a button to update 
        // and allow user to perform update in case:
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JLabel lblAmount3;
    private javax.swing.JLabel lblDiscountedAmount;
    private javax.swing.JLabel lblDiscountedAmount1;
    private javax.swing.JLabel lblDiscountedAmount2;
    private javax.swing.JLabel lblDiscountedAmount3;
    private javax.swing.JLabel lblGames;
    private javax.swing.JLabel lblGames1;
    private javax.swing.JLabel lblGames2;
    private javax.swing.JLabel lblGames3;
    private javax.swing.JLabel lblPaidAmount;
    private javax.swing.JLabel lblPaidAmount1;
    private javax.swing.JLabel lblPaidAmount2;
    private javax.swing.JLabel lblPaidAmount3;
    private javax.swing.JLabel lblPayStatus;
    private javax.swing.JLabel lblPayStatus1;
    private javax.swing.JLabel lblPayStatus2;
    private javax.swing.JLabel lblPayStatus3;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JLabel lblTime3;
    private javax.swing.JTextField paidBy;
    private javax.swing.JTextField paidBy1;
    private javax.swing.JTextField paidBy2;
    private javax.swing.JTextField paidBy3;
    private javax.swing.JTextField paidRemark;
    private javax.swing.JTextField paidRemark1;
    private javax.swing.JTextField paidRemark2;
    private javax.swing.JTextField paidRemark3;
    private javax.swing.JTextField payAmount;
    private javax.swing.JTextField payAmount1;
    private javax.swing.JTextField payAmount2;
    private javax.swing.JTextField payAmount3;
    private javax.swing.JTextField payDiscount;
    private javax.swing.JTextField payDiscount1;
    private javax.swing.JTextField payDiscount2;
    private javax.swing.JTextField payDiscount3;
    private javax.swing.JPanel tabBoardA;
    private javax.swing.JPanel tabBoardB;
    private javax.swing.JPanel tabBoardC;
    private javax.swing.JPanel tabBoardD;
    private javax.swing.JTabbedPane tabbedPaneBoard;
    // End of variables declaration//GEN-END:variables

    
}
