/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import dao.MatchDao;
import dao.PlayerDao;
import javax.swing.JOptionPane;
import model.Game;
import model.Match;
import model.Player;
import model.RoundButton;

/**
 *
 * @author stim
 */
public class PlayersOnGame extends javax.swing.JPanel {
    
    

    /**
     * Creates new form PlayersOnGame
     */
    public PlayersOnGame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelX = new javax.swing.JPanel();
        innerA = new javax.swing.JPanel();
        matchIdA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPlayerAInfoOnA = new javax.swing.JLabel();
        addPlayerAOnA = new javax.swing.JButton();
        updatePlayerAOnA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPlayerBInfoOnA = new javax.swing.JLabel();
        addPlayerBOnA = new javax.swing.JButton();
        updatePlayerBOnA = new javax.swing.JButton();
        innerB = new javax.swing.JPanel();
        matchIdB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPlayerAInfoOnB = new javax.swing.JLabel();
        addPlayerAOnB = new javax.swing.JButton();
        updatePlayerAOnB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblPlayerBInfoOnB = new javax.swing.JLabel();
        addPlayerBOnB = new javax.swing.JButton();
        updatePlayerBOnB = new javax.swing.JButton();
        innerC = new javax.swing.JPanel();
        matchIdC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPlayerAInfoOnC = new javax.swing.JLabel();
        addPlayerAOnC = new javax.swing.JButton();
        updatePlayerAOnC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblPlayerBInfoOnC = new javax.swing.JLabel();
        addPlayerBOnC = new javax.swing.JButton();
        updatePlayerBOnC = new javax.swing.JButton();
        innerD = new javax.swing.JPanel();
        matchIdD = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPlayerAInfoOnD = new javax.swing.JLabel();
        addPlayerAOnD = new javax.swing.JButton();
        updatePlayerAOnD = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblPlayerBInfoOnD = new javax.swing.JLabel();
        addPlayerBOnD = new javax.swing.JButton();
        updatePlayerBOnD = new javax.swing.JButton();

        panelX.setBackground(new java.awt.Color(0, 153, 51));
        panelX.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        innerA.setBackground(new java.awt.Color(204, 255, 204));

        matchIdA.setBackground(new java.awt.Color(255, 255, 102));
        matchIdA.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        matchIdA.setForeground(new java.awt.Color(204, 0, 0));
        matchIdA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        int midA=0;
        String nameTextA = "Name: Phone: Grade:";
        if(TriptaSports.gameOnBoardA){
            midA = TriptaSports.runningGameOnBoardA.getId();
            nameTextA = "Name: "+TriptaSports.runningGameOnBoardA.getPlayerOne()+"Phone: Grade:";
        }else{
            innerA.setEnabled(false);
        }
        matchIdA.setText("Board-A (Match Id:"+midA+")");
        matchIdA.setOpaque(true);

        jLabel1.setText("Player A");

        lblPlayerAInfoOnA.setText(nameTextA);

        addPlayerAOnA.setText("Add");
        addPlayerAOnA.setBorder(new RoundButton(10));
        addPlayerAOnA.setEnabled(innerA.isEnabled());
        addPlayerAOnA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addPlayerAOnAItemStateChanged(evt);
            }
        });
        addPlayerAOnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerAOnAActionPerformed(evt);
            }
        });

        updatePlayerAOnA.setText("Update");
        updatePlayerAOnA.setBorder(new RoundButton(10));
        updatePlayerAOnA.setEnabled(innerA.isEnabled());
        updatePlayerAOnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlayerAOnAActionPerformed(evt);
            }
        });

        jLabel3.setText("Player B");

        lblPlayerBInfoOnA.setText("Name: Phone : Ranking");

        addPlayerBOnA.setText("Add");
        addPlayerBOnA.setBorder(new RoundButton(10));
        addPlayerBOnA.setEnabled(innerA.isEnabled());
        addPlayerBOnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerBOnAActionPerformed(evt);
            }
        });

        updatePlayerBOnA.setText("Update");
        updatePlayerBOnA.setBorder(new RoundButton(10));
        updatePlayerBOnA.setEnabled(innerA.isEnabled());
        updatePlayerBOnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlayerBOnAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout innerALayout = new javax.swing.GroupLayout(innerA);
        innerA.setLayout(innerALayout);
        innerALayout.setHorizontalGroup(
            innerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(innerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matchIdA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(lblPlayerAInfoOnA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(innerALayout.createSequentialGroup()
                        .addGroup(innerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(innerALayout.createSequentialGroup()
                                .addComponent(addPlayerAOnA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updatePlayerAOnA))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(innerALayout.createSequentialGroup()
                                .addComponent(addPlayerBOnA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updatePlayerBOnA)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPlayerBInfoOnA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        innerALayout.setVerticalGroup(
            innerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchIdA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPlayerAInfoOnA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(innerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerAOnA)
                    .addComponent(updatePlayerAOnA))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPlayerBInfoOnA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(innerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerBOnA)
                    .addComponent(updatePlayerBOnA))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        panelX.add(innerA);

        innerB.setBackground(new java.awt.Color(204, 204, 0));

        matchIdB.setBackground(new java.awt.Color(255, 255, 102));
        matchIdB.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        matchIdB.setForeground(new java.awt.Color(204, 0, 0));
        matchIdB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        int midB=0;
        String nameTextB = "Name: Phone: Grade:";
        if(TriptaSports.gameOnBoardB){
            midB = TriptaSports.runningGameOnBoardB.getId();
            nameTextB = "Name: "+TriptaSports.runningGameOnBoardB.getPlayerOne()+"Phone: Grade:";
        }else{

            innerB.setEnabled(false);

        }
        matchIdB.setText("Board-B (Match Id:"+midB+")");
        matchIdB.setOpaque(true);

        jLabel2.setText("Player A");

        lblPlayerAInfoOnB.setText(nameTextB);

        addPlayerAOnB.setText("Add");
        addPlayerAOnB.setBorder(new RoundButton(10));
        addPlayerAOnB.setEnabled(innerB.isEnabled());

        updatePlayerAOnB.setText("Update");
        updatePlayerAOnB.setBorder(new RoundButton(10));
        updatePlayerAOnB.setEnabled(innerB.isEnabled());

        jLabel4.setText("Player B");

        lblPlayerBInfoOnB.setText("Name: Phone : Ranking");

        addPlayerBOnB.setText("Add");
        addPlayerBOnB.setBorder(new RoundButton(10));
        addPlayerBOnB.setEnabled(innerB.isEnabled());

        updatePlayerBOnB.setText("Update");
        updatePlayerBOnB.setBorder(new RoundButton(10));
        updatePlayerBOnB.setEnabled(innerB.isEnabled());

        javax.swing.GroupLayout innerBLayout = new javax.swing.GroupLayout(innerB);
        innerB.setLayout(innerBLayout);
        innerBLayout.setHorizontalGroup(
            innerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchIdB, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(innerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(innerBLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(innerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPlayerAInfoOnB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(innerBLayout.createSequentialGroup()
                            .addGroup(innerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(innerBLayout.createSequentialGroup()
                                    .addComponent(addPlayerAOnB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updatePlayerAOnB))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(innerBLayout.createSequentialGroup()
                                    .addComponent(addPlayerBOnB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updatePlayerBOnB)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(lblPlayerBInfoOnB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        innerBLayout.setVerticalGroup(
            innerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchIdB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(innerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(innerBLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblPlayerAInfoOnB)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(innerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPlayerAOnB)
                        .addComponent(updatePlayerAOnB))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblPlayerBInfoOnB)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(innerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPlayerBOnB)
                        .addComponent(updatePlayerBOnB))
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        panelX.add(innerB);

        innerC.setBackground(new java.awt.Color(204, 204, 0));

        matchIdC.setBackground(new java.awt.Color(255, 255, 102));
        matchIdC.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        matchIdC.setForeground(new java.awt.Color(204, 0, 0));
        matchIdC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        int midC=0;
        String nameTextC = "Name: Phone: Grade:";
        if(TriptaSports.gameOnBoardC){
            midC = TriptaSports.runningGameOnBoardC.getId();
            nameTextC = "Name: "+TriptaSports.runningGameOnBoardC.getPlayerOne()+"Phone: Grade:";
        }else{
            innerC.setEnabled(false);
        }
        matchIdC.setText("Board-C (Match Id:"+midC+")");
        matchIdC.setOpaque(true);

        jLabel5.setText("Player A");

        lblPlayerAInfoOnC.setText(nameTextC);

        addPlayerAOnC.setText("Add");
        addPlayerAOnC.setBorder(new RoundButton(10));
        addPlayerAOnC.setEnabled(innerC.isEnabled());

        updatePlayerAOnC.setText("Update");
        updatePlayerAOnC.setBorder(new RoundButton(10));
        updatePlayerAOnC.setEnabled(innerC.isEnabled());

        jLabel6.setText("Player B");

        lblPlayerBInfoOnC.setText("Name: Phone : Ranking");

        addPlayerBOnC.setText("Add");
        addPlayerBOnC.setBorder(new RoundButton(10));
        addPlayerBOnC.setEnabled(innerC.isEnabled());

        updatePlayerBOnC.setText("Update");
        updatePlayerBOnC.setBorder(new RoundButton(10));
        updatePlayerBOnC.setEnabled(innerC.isEnabled());

        javax.swing.GroupLayout innerCLayout = new javax.swing.GroupLayout(innerC);
        innerC.setLayout(innerCLayout);
        innerCLayout.setHorizontalGroup(
            innerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchIdC, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(innerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(innerCLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(innerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPlayerAInfoOnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(innerCLayout.createSequentialGroup()
                            .addGroup(innerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(innerCLayout.createSequentialGroup()
                                    .addComponent(addPlayerAOnC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updatePlayerAOnC))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(innerCLayout.createSequentialGroup()
                                    .addComponent(addPlayerBOnC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updatePlayerBOnC)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(lblPlayerBInfoOnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        innerCLayout.setVerticalGroup(
            innerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchIdC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(innerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(innerCLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblPlayerAInfoOnC)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(innerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPlayerAOnC)
                        .addComponent(updatePlayerAOnC))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblPlayerBInfoOnC)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(innerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPlayerBOnC)
                        .addComponent(updatePlayerBOnC))
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        panelX.add(innerC);

        innerD.setBackground(new java.awt.Color(204, 255, 204));

        matchIdD.setBackground(new java.awt.Color(255, 255, 102));
        matchIdD.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        matchIdD.setForeground(new java.awt.Color(204, 0, 0));
        matchIdD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        int midD=0;
        String nameTextD = "Name: Phone: Grade:";
        if(TriptaSports.gameOnBoardD){
            midD = TriptaSports.runningGameOnBoardD.getId();
            nameTextD = "Name: "+TriptaSports.runningGameOnBoardD.getPlayerOne()+"Phone: Grade:";
        }else{
            innerD.setEnabled(false);
        }
        matchIdD.setText("Board-D (Match Id:"+midD+")");
        matchIdD.setOpaque(true);

        jLabel7.setText("Player A");

        lblPlayerAInfoOnD.setText(nameTextD);

        addPlayerAOnD.setText("Add");
        addPlayerAOnD.setBorder(new RoundButton(10));
        addPlayerAOnD.setEnabled(innerD.isEnabled());

        updatePlayerAOnD.setText("Update");
        updatePlayerAOnD.setBorder(new RoundButton(10));
        updatePlayerAOnD.setEnabled(innerD.isEnabled());

        jLabel8.setText("Player B");

        lblPlayerBInfoOnD.setText("Name: Phone : Ranking");

        addPlayerBOnD.setText("Add");
        addPlayerBOnD.setBorder(new RoundButton(10));
        addPlayerBOnD.setEnabled(innerD.isEnabled());

        updatePlayerBOnD.setText("Update");
        updatePlayerBOnD.setBorder(new RoundButton(10));
        updatePlayerBOnD.setEnabled(innerD.isEnabled());

        javax.swing.GroupLayout innerDLayout = new javax.swing.GroupLayout(innerD);
        innerD.setLayout(innerDLayout);
        innerDLayout.setHorizontalGroup(
            innerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchIdD, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(innerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(innerDLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(innerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPlayerAInfoOnD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(innerDLayout.createSequentialGroup()
                            .addGroup(innerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(innerDLayout.createSequentialGroup()
                                    .addComponent(addPlayerAOnD)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updatePlayerAOnD))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(innerDLayout.createSequentialGroup()
                                    .addComponent(addPlayerBOnD)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updatePlayerBOnD)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(lblPlayerBInfoOnD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        innerDLayout.setVerticalGroup(
            innerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerDLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(matchIdD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(innerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(innerDLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblPlayerAInfoOnD)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(innerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPlayerAOnD)
                        .addComponent(updatePlayerAOnD))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblPlayerBInfoOnD)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(innerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPlayerBOnD)
                        .addComponent(updatePlayerBOnD))
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        panelX.add(innerD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelX, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerAOnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerAOnAActionPerformed
        // playerA on BoardA:
        Player playerOne = new PlayerAddOptionPane().showOption("Add PlayerA on BOARD-A");
        System.out.println(playerOne.toString());
        int id = new PlayerDao().setPlayerOnGame(playerOne);
        if(id>0){
           TriptaSports.runningGameOnBoardA.setPlayerOne(playerOne.getName());
           TriptaSports.currentPlayers.put("AA", playerOne);
          if(new MatchDao().updatePlayer(TriptaSports.runningGameOnBoardA)){
              JOptionPane.showMessageDialog(null, "Player updated!");
          }else{
              JOptionPane.showMessageDialog(null, "Player update Failed!");
          }
          
            lblPlayerAInfoOnA.setText("Name:"+playerOne.getName()
                    +", Phone:"+playerOne.getPhone()
                    +", Ranking:"+playerOne.getEmail());
        }
    }//GEN-LAST:event_addPlayerAOnAActionPerformed

    private void addPlayerBOnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerBOnAActionPerformed
        // PlayerB on BoardB
        // playerA on BoardA:
        Player playerTwo = new PlayerAddOptionPane().showOption("Add PlayerB on BOARD-A");
        System.out.println(playerTwo.toString());
        int id = new PlayerDao().setPlayerOnGame(playerTwo);
        if(id>0){
           TriptaSports.runningGameOnBoardA.setPlayerTwo(playerTwo.getName());
           TriptaSports.currentPlayers.put("AB", playerTwo);
          if(new MatchDao().updatePlayer(TriptaSports.runningGameOnBoardA)){
              JOptionPane.showMessageDialog(null, "Player updated!");
          }else{
              JOptionPane.showMessageDialog(null, "Player update Failed!");
          }
          
            lblPlayerBInfoOnA.setText("Name:"+playerTwo.getName()
                    +", Phone:"+playerTwo.getPhone()
                    +", Grade:"+playerTwo.getEmail());
        }
    }//GEN-LAST:event_addPlayerBOnAActionPerformed

    private void updatePlayerAOnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlayerAOnAActionPerformed
        //update playerA on BoardA:
        Player playerOne = new PlayerAddOptionPane().showOption("Update PlayerA on BOARD-A");
        System.out.println(playerOne.toString());
        TriptaSports.runningGameOnBoardA.setPlayerOne(playerOne.getName());
        TriptaSports.currentPlayers.put("AA", playerOne);
        if(new MatchDao().updatePlayer(TriptaSports.runningGameOnBoardA)){
            JOptionPane.showMessageDialog(null, "Player updated!");
            lblPlayerAInfoOnA.setText("Name:"+playerOne.getName()
                    +", Phone:"+playerOne.getPhone()
                    +", Grade:"+playerOne.getEmail());
        }
        else{
            JOptionPane.showMessageDialog(null, "Player update Failed!");
        }
        
        
    }//GEN-LAST:event_updatePlayerAOnAActionPerformed

    private void updatePlayerBOnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlayerBOnAActionPerformed
        // update playerB on BoardA:
         Player playerTwo = new PlayerAddOptionPane().showOption("Update PlayerB on BOARD-A");
        System.out.println(playerTwo.toString());
        TriptaSports.runningGameOnBoardA.setPlayerTwo(playerTwo.getName());
        TriptaSports.currentPlayers.put("AB", playerTwo);
        if(new MatchDao().updatePlayer(TriptaSports.runningGameOnBoardA)){
            JOptionPane.showMessageDialog(null, "Player updated!");
            lblPlayerAInfoOnA.setText("Name:"+playerTwo.getName()
                    +", Phone:"+playerTwo.getPhone()
                    +", Grade:"+playerTwo.getEmail());
        }
        else{
            JOptionPane.showMessageDialog(null, "Player update Failed!");
        }
        
    }//GEN-LAST:event_updatePlayerBOnAActionPerformed

    private void addPlayerAOnAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addPlayerAOnAItemStateChanged
        // TODO add your handling code here:
        System.out.println("State changed!");
    }//GEN-LAST:event_addPlayerAOnAItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayerAOnA;
    private javax.swing.JButton addPlayerAOnB;
    private javax.swing.JButton addPlayerAOnC;
    private javax.swing.JButton addPlayerAOnD;
    private javax.swing.JButton addPlayerBOnA;
    private javax.swing.JButton addPlayerBOnB;
    private javax.swing.JButton addPlayerBOnC;
    private javax.swing.JButton addPlayerBOnD;
    private javax.swing.JPanel innerA;
    private javax.swing.JPanel innerB;
    private javax.swing.JPanel innerC;
    private javax.swing.JPanel innerD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblPlayerAInfoOnA;
    private javax.swing.JLabel lblPlayerAInfoOnB;
    private javax.swing.JLabel lblPlayerAInfoOnC;
    private javax.swing.JLabel lblPlayerAInfoOnD;
    private javax.swing.JLabel lblPlayerBInfoOnA;
    private javax.swing.JLabel lblPlayerBInfoOnB;
    private javax.swing.JLabel lblPlayerBInfoOnC;
    private javax.swing.JLabel lblPlayerBInfoOnD;
    private javax.swing.JLabel matchIdA;
    private javax.swing.JLabel matchIdB;
    private javax.swing.JLabel matchIdC;
    private javax.swing.JLabel matchIdD;
    private javax.swing.JPanel panelX;
    private javax.swing.JButton updatePlayerAOnA;
    private javax.swing.JButton updatePlayerAOnB;
    private javax.swing.JButton updatePlayerAOnC;
    private javax.swing.JButton updatePlayerAOnD;
    private javax.swing.JButton updatePlayerBOnA;
    private javax.swing.JButton updatePlayerBOnB;
    private javax.swing.JButton updatePlayerBOnC;
    private javax.swing.JButton updatePlayerBOnD;
    // End of variables declaration//GEN-END:variables
}
